version: '3.9'

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:24
    environment:
      BITCOIN_DATA: /bitcoin_data
    volumes:
      - ./bitcoin_data:/bitcoin_data
    command:
      # user=mempool password=mempool
      --datadir=/bitcoin_data/
      --rpcauth=mempool:566ace4b8835ffc2b6afe62bc9572f46$$71289034ea88f6a9e78af51c5b2f2501a2f3c3b47e9cdcfca773353d61996734
      --printtoconsole=1
      --regtest=1
      --server=1
      --rest=1
      --rpcallowip=0.0.0.0/0
      --rpcallowip=172.16/12
      --txindex=1 
      --rpcbind=0.0.0.0:18443
      --rpcport=18443
      --port=18444
    ports:
      - '18443:18443' # rpc port
      - '18444:18444' # p2p port
    
  bitcoin-init:
    # Just mines 140 blocks once bitcoind service is up.
    image: appropriate/curl
    depends_on:
      - bitcoind
    volumes:
      - ./bitcoin-init.sh:/bitcoin-init.sh
    command: /bin/sh /bitcoin-init.sh


  mempool-web:
    image: mempool/frontend:v2.5.0
    command: "./wait-for mempool-db:3310 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: 8080
      BACKEND_MAINNET_HTTP_HOST: mempool-api

      # new stuff below
      TESTNET_ENABLED: "false"
      SIGNET_ENABLED: "false"
      LIQUID_ENABLED: "false"
      LIQUID_TESTNET_ENABLED: "false"
      BISQ_ENABLED: "false"
      BISQ_SEPARATE_BACKEND: "false"
      ITEMS_PER_PAGE: 10
      KEEP_BLOCKS_AMOUNT: 8
      NGINX_PROTOCOL: http
      NGINX_HOSTNAME: mempool-api
      NGINX_PORT: 80
      BLOCK_WEIGHT_UNITS: 4000000
      MEMPOOL_BLOCKS_AMOUNT: 8
      BASE_MODULE: mempool
      MEMPOOL_WEBSITE_URL: https://mempool.space
      LIQUID_WEBSITE_URL: https://liquid.network
      BISQ_WEBSITE_URL: https://bisq.markets
      MINING_DASHBOARD: "false"
      AUDIT: "false"
      MAINNET_BLOCK_AUDIT_START_HEIGHT: 0
      TESTNET_BLOCK_AUDIT_START_HEIGHT: 0
      SIGNET_BLOCK_AUDIT_START_HEIGHT: 0
      LIGHTNING: "false"
      FULL_RBF_ENABLED: "false"
      HISTORICAL_PRICE: "false"

    restart: on-failure
    ports:
      - 1234:8080

  mempool-api:
    image: mempool/backend:v2.5.0
    command: "./wait-for-it.sh mempool-db:3310 --timeout=720 --strict -- ./start.sh"
    restart: on-failure
    environment:
      MEMPOOL_NETWORK: mainnet
      MEMPOOL_BACKEND: electrum
      MEMPOOL_ENABLED: "true"
      MEMPOOL_HTTP_PORT: 8999
      MEMPOOL_SPAWN_CLUSTER_PROCS: 0
      MEMPOOL_API_URL_PREFIX: /api/v1/
      MEMPOOL_POLL_RATE_MS: 2000
      MEMPOOL_CACHE_DIR: ./cache
      MEMPOOL_CLEAR_PROTECTION_MINUTES: 20
      MEMPOOL_RECOMMENDED_FEE_PERCENTILE: 50
      MEMPOOL_BLOCK_WEIGHT_UNITS: 4000000
      MEMPOOL_INITIAL_BLOCKS_AMOUNT: 8
      MEMPOOL_MEMPOOL_BLOCKS_AMOUNT: 8
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: 11000
      MEMPOOL_BLOCKS_SUMMARIES_INDEXING: "false"
      MEMPOOL_USE_SECOND_NODE_FOR_MINFEE: "false"
      MEMPOOL_EXTERNAL_ASSETS: ""
      MEMPOOL_EXTERNAL_MAX_RETRY: 1
      MEMPOOL_EXTERNAL_RETRY_INTERVAL: 0
      MEMPOOL_USER_AGENT: mempool
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: debug
      MEMPOOL_AUTOMATIC_BLOCK_REINDEXING: "false"
      MEMPOOL_POOLS_JSON_URL: https://raw.githubusercontent.com/mempool/mining-pools/master/pools-v2.json
      MEMPOOL_POOLS_JSON_TREE_URL: https://api.github.com/repos/mempool/mining-pools/git/trees/master
      MEMPOOL_AUDIT: "false"
      MEMPOOL_ADVANCED_GBT_AUDIT: "false"
      MEMPOOL_ADVANCED_GBT_MEMPOOL: "false"
      MEMPOOL_CPFP_INDEXING: "false"
      MEMPOOL_DISK_CACHE_BLOCK_INTERVAL: 6

      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: 18443
      CORE_RPC_USERNAME: mempool
      CORE_RPC_PASSWORD: mempool
      CORE_RPC_TIMEOUT: 60000

      ELECTRUM_HOST: mempool-electrs
      ELECTRUM_PORT: 60401
      ELECTRUM_TLS_ENABLED: "false"

      DATABASE_ENABLED: "true"
      DATABASE_HOST: mempool-db
      DATABASE_PORT: 3310
      DATABASE_DATABASE: mempool
      DATABASE_USERNAME: mempool
      DATABASE_PASSWORD: mempool
      DATABASE_TIMEOUT: 180000

  mempool-db:
    image: mariadb:10.5.8
    environment:
      MYSQL_DATABASE: mempool
      MYSQL_USER: mempool
      MYSQL_PASSWORD: mempool
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_TCP_PORT: 3310
    restart: on-failure
    volumes:
      - ./mysql_data:/var/lib/mysql
    expose:
      - '3310'
      - '13310'
    ports:
      - '13310:3310'
      - '3310:3310'

  mempool-electrs:
    image: mempool/electrs:latest
    restart: on-failure
    ports:
      - 3009:3009
      - 60401:60401
    entrypoint:
      /bin/electrs
    command: |
      --network regtest
      --daemon-dir /bitcoin_data
      --daemon-rpc-addr bitcoind:18443
      --electrum-rpc-addr 0.0.0.0:60401
      --cookie mempool:mempool
      --address-search
      --index-unspendables
      --http-addr 0.0.0.0:3009
      --db-dir /electrs
      --cors '*'
    volumes:
    - './electrs_data:/electrs'
    - './bitcoin_data:/bitcoin_data'

networks: {}
